### ISSUE TITLE
CMDB model页面未展示模型实例的数量

### ISSUE THREAD

**Issue by roger060353** [WeOps-Lab/lite-cmdb-web#3]
<img width="792" alt="企业微信截图_c7e3141d-f80e-4caa-a4d8-69a54558ea0b" src="https://github.com/user-attachments/assets/8e72108a-4379-4541-bb76-cbcebdf7ced3">

**Comment by CharlesWhj** [comment]
已解决

**Comment by CharlesWhj** [comment]
已解决
